name: release

on:
  push:
    branches: [master]
    tags: ["!*"]

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      # == check before release ==
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.x # node-lts
      - run: npm install can-npm-publish
      - run: npx can-npm-publish

      # == prepare release ==
      - run: npm ci
      - run: npm build
      - run: npm test

      # == release ==
      - name: check version and add tag
        run: ./release.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
